const { log } = require('console')
const os = require('os')
const path = require('path')
const {add} = require('./math.js')
// console.log(os.type())
// console.log(os.version())
// console.log(__dirname)
console.log(path.dirname)
console.log(add(2,3))